name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Uses EC2 instance as the runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub  # Optional if pushing to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t my-html-app .

    - name: Stop and Remove Old Container (if exists)
      run: |
        docker stop my-html-container || true
        docker rm my-html-container || true

    - name: Run New Container
      run: docker run -d -p 8080:80 --name my-html-container my-html-app
